version: '3.7'
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: docker/php/fpm/Dockerfile
    image: 376372006699.dkr.ecr.us-east-1.amazonaws.com/hubseg-v2-app:${IMAGE_TAG:-latest}
    container_name: hubseg-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    networks:
      - hubseg-network

  # NGINX Service
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: 376372006699.dkr.ecr.us-east-1.amazonaws.com/hubseg-v2-nginx:${IMAGE_TAG:-latest}
    container_name: hubseg-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - hubseg-network

# Docker Networks
networks:
  hubseg-network:
    driver: bridge
